### ISSUE TITLE
Negative electricity demand when temporal resolution is 24h

### ISSUE THREAD

**Issue by cerealice** [PyPSA/pypsa-eur#1145] opened 2024-07-11 12:38 UTC
## Checklist

- [ ] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate. v 0.11.0
- [ ] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

Running the config file for a clustering temporal resolution of more than 1h for the electricity sector, in "scripts/prepare_sector_network.py" I believe there is a bug at lines 3202-3206
factor = (
            1
            - industrial_demand.loc[loads_i, "current electricity"].sum()
            / n.loads_t.p_set[loads_i].sum().sum()
        )

In this case the numerator is an annual value while the denominator is not. I would fix it with some code like this:
Line 2562: timestep = n.snapshot_weightings.iloc[0,0]
Then the previous lines would be:
        factor = (
            1
            - industrial_demand.loc[loads_i, "current electricity"].sum()
            / (n.loads_t.p_set[loads_i].sum().sum()*timestep)
        )

Let me know :)

**Comment by fneum** [comment] 2024-09-24 05:26
duplicate of #1278

**Closed by fneum** 2024-09-24 05:26 UTC
Labels: bug
