### ISSUE TITLE
Issues on snakemake + windows 

### ISSUE THREAD

**Issue by matteodefelice** [PyPSA/pypsa-eur#287] opened 2021-11-08 21:12 UTC
I have just installed `pypsa-eur` with conda on my Windows 11 machine. I have created the new environment without problems. I started following the tutorial and then I had an issue when launching `snakemake -j 1 results/networks/elec_s_6_ec_lcopt_Co2L-24H.nc`. I got the error `Error: 'mv' is not recognized as an internal or external command` and then I replace all the `mv` with `move` in the snakemake file. But then again (always adding `--keep-target-files`):

```
[Mon Nov  8 22:08:14 2021]
rule retrieve_natura_raster:
    input: zenodo.org/record/4706686/files/natura.tiff
    output: resources/natura.tiff
    jobid: 13
    resources: tmpdir=C:\Users\matte\AppData\Local\Temp

The system cannot find the path specified.
[Mon Nov  8 22:08:14 2021]
Error in rule retrieve_natura_raster:
    jobid: 13
    output: resources/natura.tiff
    shell:
        move zenodo.org/record/4706686/files/natura.tiff resources/natura.tiff
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
```

Then I tried instead `snakemake -j 1 solve_all_networks` but I got another error:
```

[Mon Nov  8 22:10:03 2021]
rule build_load_data:
    output: resources/load.csv
    log: logs/build_load_data.log
    jobid: 12
    resources: tmpdir=C:\Users\matte\AppData\Local\Temp

INFO:__main__:Retrieving load data from 'https://data.open-power-system-data.org/time_series/2019-06-05/time_series_60min_singleindex.csv'.
Traceback (most recent call last):
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\http\client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\http\client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\http\client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\http\client.py", line 1034, in _send_output
    self.send(msg)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\http\client.py", line 974, in send
    self.connect()
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\http\client.py", line 1448, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matte\OneDrive\local\work\pypsa-eur\.snakemake\scripts\tmpq9hny4zh.build_load_data.py", line 213, in <module>
    load = load_timeseries(url, years, countries, powerstatistics)
  File "C:\Users\matte\OneDrive\local\work\pypsa-eur\.snakemake\scripts\tmpq9hny4zh.build_load_data.py", line 82, in load_timeseries
    return (pd.read_csv(fn, index_col=0, parse_dates=[0], date_parser=date_parser)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\pandas\io\common.py", line 558, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\pandas\io\common.py", line 289, in _get_filepath_or_buffer
    req = urlopen(filepath_or_buffer)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\pandas\io\common.py", line 195, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
[Mon Nov  8 22:10:05 2021]
Error in rule build_load_data:
    jobid: 12
    output: resources/load.csv
    log: logs/build_load_data.log (check log file(s) for error message)

Traceback (most recent call last):
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\snakemake\executors\__init__.py", line 593, in _callback
    raise ex
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\snakemake\executors\__init__.py", line 579, in cached_or_run
    run_func(*args)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\snakemake\executors\__init__.py", line 2461, in run_wrapper
    raise ex
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\snakemake\executors\__init__.py", line 2418, in run_wrapper
    run(
  File "C:\Users\matte\OneDrive\local\work\pypsa-eur\Snakefile", line 134, in __rule_build_load_data
    regions_onshore="resources/regions_onshore.geojson",
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\snakemake\script.py", line 1371, in script
    executor.evaluate()
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\snakemake\script.py", line 381, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\snakemake\script.py", line 582, in execute_script
    self._execute_cmd(
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\snakemake\script.py", line 414, in _execute_cmd
    return shell(
  File "C:\Users\matte\miniconda3\envs\pypsa-eur\lib\site-packages\snakemake\shell.py", line 266, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:/Users/matte/miniconda3/envs/pypsa-eur/python.exe "C:\Users\matte\OneDrive\local\work\pypsa-eur\.snakemake\scripts\tmpq9hny4zh.build_load_data.py"' returned non-zero exit status 1.
Shutting down, this might take some time.
```

What might be the problem? Is it possible to run this on a Windows machine?

**Comment by euronion** [comment] 2021-11-09 09:46
It may be linked to windows (you're using a new machine i presume since you're using Windows 11) or to your `requests` library version combined with the relatively fresh certificate (or possibly outdated certificate when you ran the workflow) of `open-power-system-data.org`:

I cannot reproduce the problem on Windows 10 with `requests=2.26.0`.
Can you check your `requests` version, maybe update, and try again?

In general: If you use PyPSA-EUR in WSL for Windows, then you don't need to adjust the workflow in any way (e.g. `mv` -> `move`). PyPSA-EUR is fully compatible with WSL :)

**Comment by matteodefelice** [comment] 2021-11-09 10:02
I had the version 2.25. Upgrading to 2.26 did not change anything. I have also upgraded the entire environment but with no success. Regarding the WSL, I haven't tried to set it up, I will give a look at it. I am also trying to install it on a virtualised Ubuntu but currently bioconda seems down and I cannot create the environment...

**Comment by euronion** [comment] 2021-11-09 16:21
I'm blindly guessing the problem is with how `requests` get's it's certificates on Windows. (You could check your windows certificate store using `mmc` and the `certificate` snap-in (The Let's Encrypt/R3 and/or ISRG Root X1 certificate may be outdated there?).

Have a look at WSL. Setup is pretty simple and it should get rid of the issue.

Sorry, I can't reproduce it locally and judging from the comments I found online on this issue it is very windows+`requests` specific.

**Comment by euronion** [comment] 2021-11-10 08:15
I have another user who contacted me about the same issue (´certificate verify failed: certificate has expired (_ssl.c:1129)` when downloading the OPSD data). Also on Windows (not sure about the version).

**Comment by fneum** [comment] 2021-11-10 17:06
Maybe #289 solved the problem.

**Comment by matteodefelice** [comment] 2021-11-13 21:50
From my side we can close it because I switched to WSL where everything is working perfectly.

**Comment by euronion** [comment] 2021-11-14 17:50
Ok, happy to hear! Closing as solveable by using WSL / cannot reproduce on our Windows systems / error probably caused outside of PyPSA-EUR.

**Closed by euronion** 2021-11-14 17:50 UTC
Labels: bug
